### PR TITLE
[Web] Fix sound play while AudioContext is suspended

### LINKED ISSUE #8238: Sounds in html5 not started until first user touch
**Describe the bug (REQUIRED)**

**ERROR:SOUND: Out of sound data instance slots (256). Increase the project setting 'sound.max_sound_instances'\n"**

Browser block sound play until first user touch. So sounds not started and player reach limit.

This error not block player from playing in my case. But if someone use cb of sounds for logic it can break there games.

This example from my game. I play step sounds when player move.

**This is correct. I make touch and you can hear sounds.**

https://github.com/defold/defold/assets/2655263/3105c490-8453-48a8-a434-dbc35f8531bb

**This is error.**

https://github.com/defold/defold/assets/2655263/84357247-64f6-42c2-828a-75a3433ed960

Also you can hear in video that all sounds start playing on first touch.

**To Reproduce (REQUIRED)**
1. Start web build
2. Some sounds
3. Sounds not finished until user make first touch(browser not allow to play sounds untils first click or touch)
4. You get error when reach limit.

**Expected behavior (REQUIRED)**
Not sure what is best case for that scenario. 
If it possible sounds should started and finished. If not mb we need sound.can_play() method

**Defold version (REQUIRED):**
  - Version 1.6.1

**Platforms (REQUIRED):**
 - Platforms: HTML5

### PR DESCRIPTION
**Pull request by ekharkunov**
Fixes #8238 

### Technical changes
If AudioContext is suspended we calculate play offset but don't create audio buffers and audio sources on JS side.

## PR checklist

* [x] Code
	* [x] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [x] Add comments where needed
* [x] Documentation
	* [x] Make sure that API documentation is updated in code comments
	* [x] Make sure that manuals are updated (in github.com/defold/doc)
* [x] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [x] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [x] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [x] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [x] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

**Comment by AGulev** [comment]
What will happen if many sounds started without having context and then later game got the context. Will all of them play at the same time?

**Comment by ekharkunov** [comment]
> What will happen if many sounds started without having context and then later game got the context. Will all of them play at the same time?

I've test in following setup:
* Play 30 seconds sound in `init` function of bootstrap collection.
* Print all messages from play callback
So when I load a page - console has log with 'sound_done' message immediately. So sound is removed after that. As result - when we start playing lots of sound without active audio context - they are all completed and when user click on canvas - no sounds will be played.

**Comment by AGulev** [comment]
>So when I load a page - console has log with 'sound_done' message immediately. So sound is removed after that. 

Good. But in case when I run music that would probably mean I will never hear it because instead playing it will end immediately.

>As result - when we start playing lots of sound without active audio context - they are all completed and when user click on canvas - no sounds will be played.

What will happen if I play sound with looping option?

-----
What I thought about, maybe it's possible to consume sound buffers silently like if sound device exist. So we kinda play sounds but without playing it. And when the engine gets sound context it will continue playing from the place it is at now (I didn't investigate if it's possible to implement this way, but it would help to avoid all the issues with immediate callback and music that we start once in the beginning and will never hear because of that)

**Comment by ekharkunov** [comment]
> What I thought about, maybe it's possible to consume sound buffers silently like if sound device exist. So we kinda play sounds but without playing it. And when the engine gets sound context it will continue playing from the place it is at now (I didn't investigate if it's possible to implement this way, but it would help to avoid all the issues with immediate callback and music that we start once in the beginning and will never hear because of that)

Almost can be done. What I found:
* if prevent buffer from queuing here https://github.com/defold/defold/blob/dev/engine/sound/src/sound.cpp#L1476 - sound played much more faster than it should be. If happend because we based on `free_slots` that returned from audio device (https://github.com/defold/defold/blob/dev/engine/sound/src/sound.cpp#L1459)
* if prevent buffer creating and playing on JS side - it almost works as needed because it based only on buffer length and `currentTime` from AudioContext https://github.com/defold/defold/blob/dev/engine/sound/src/js/library_sound.js#L66. But it's not working completely right because AudioContext.currentTime isn't changed while AudioContext stay in 'suspended' state.
It needs to be somehow simulate running timer while AudioContext is suspended and than use that elapsed time during `_freeBufferSlots` calculation.

**Comment by AGulev** [comment]
> * if prevent buffer creating and playing on JS side - it almost works as needed because it based only on buffer length and `currentTime` from AudioContext https://github.com/defold/defold/blob/dev/engine/sound/src/js/library_sound.js#L66. But it's not working completely right because AudioContext.currentTime isn't changed while AudioContext stay in 'suspended' state.
>   It needs to be somehow simulate running timer while AudioContext is suspended and than use that elapsed time during `_freeBufferSlots` calculation.

What if we get 
>var initTime = Date.now() / 1000;

When we request to play sound without having a context. 
And then use 
> currentTime = (Date.now() / 1000) -  initTime

instead of `shared.audioCtx.currentTime` if context doesn't exist and then when context created save latest "synthetic" current time before creation and continue to use it as:
>currentTime  = currentTime  + shared.audioCtx.currentTime;

not sure if it will work, but if so, then we avoid any actions from user side, because for the engine it will be like engine plays sound without playing until it can actually play it

**Comment by ekharkunov** [comment]
> > * if prevent buffer creating and playing on JS side - it almost works as needed because it based only on buffer length and `currentTime` from AudioContext https://github.com/defold/defold/blob/dev/engine/sound/src/js/library_sound.js#L66. But it's not working completely right because AudioContext.currentTime isn't changed while AudioContext stay in 'suspended' state.
> >   It needs to be somehow simulate running timer while AudioContext is suspended and than use that elapsed time during `_freeBufferSlots` calculation.
> 
> What if we get
> 
> > var initTime = Date.now() / 1000;
> 
> When we request to play sound without having a context for the first time and then use
> 
> > currentTime = (Date.now() / 1000) -  initTime
> 
> instead of `shared.audioCtx.currentTime` if context doesn't exist and then when context created save latest "synthetic" current time before creation and continue to use it as:
> 
> > currentTime  = currentTime  + shared.audioCtx.currentTime;
> 
> not sure if it will work, but if so, then we avoid any actions from user side, because for the engine it will be like engine plays sound without playing until it can actually play it

I'm trying several hours to implement in such way. But can't resolve issue to start sound from the middle. Now it correctly calculated and send 'sound_done' message but sound plays with the shift.

**Review by AGulev — DISMISSED** [review]
I think this implementation is the best for the end user, because it doesn't require to think about the sound context and make it possible to keep logic as is.

But taking into account this is a bit of a hack, I would prefer to have a couple of sentences comment right in code with link to this PR where we had conversation about implementation, so the next time it will be touched, we know what's going on and why

**Review by AGulev — APPROVED** [review]
👍

**Pull request merged**
