### PR TITLE
issue-editor2-2698-value-out-of-range-when-zooming-too-far-out-in-perspective-proj

### PR DESCRIPTION
**Pull request by madwareru**
Modified offset-scaled function so it wouldn't be possible to zoom too far out

Closes defold/editor2-issues#2698

### CODE REVIEW

**Review by matgis-king — CHANGES_REQUESTED** [review]
Nice work diagnosing the issue! :heart:

However, I would probably try to fix this by clamping the value we supply for the `scale-factor` argument to the `offset-scaled` function rather than hard-coding a workaround in the `offset-scaled` function itself.

**Comment by britzl** [comment]
@madwareru have you had a chance to review the feedback @matgis-king gave?

**Comment by madwareru** [comment]
@britzl to be honest it's not clear for me how to solve this issue by clamping input parameters instead of output of the function. After I read this review I felt confused and didn't found a way to settle with a task. May be I need some help on it

**Comment by matgis** [comment]
What I mean is, `offset-scaled` is a general-purpose function. Here you've patched in a fix for a particular situation into `offset-scaled`, but I'd prefer if you instead fixed the issue at the point where `offset-scaled` is being called.

I'd suggest simply clamping the `scale-factor` argument to a sensible range. I think that should do the trick.

**Pull request closed without merging**
