### PR TITLE
Added a preference field for setting a custom keymap path

### PR DESCRIPTION
**Pull request by saikyun**
Two questions:
- How do I add documentation for the keymap? E.g. give an example keymap.
- I got compilation errors when trying to run `lein test`. I haven't modified the tests, so I don't think that's my fault. :) What can I do to resolve that?

### CODE REVIEW

**Review by matgis — APPROVED** [review]
Code looks good to me, but currently the build is blocked by an error during editor tests. Once that has been resolved and we're sure the tests pass, I'm fine with merging this.

**Comment by britzl** [comment]
> the build is blocked by an error during editor tests

The problem was that our GitHub Actions workflow files were configured to run for the "pull_request" event. This prevented the use of GitHub Secrets such as access tokens etc. The correct approach is to trigger on the "pull_request_target" event. I've changed this for the "dev" and "editor-dev" branch so any future PR or update to this PR from a fork should be able to successfully run the tests.

**Comment by britzl** [comment]
> How do I add documentation for the keymap

A good place to add the documentation is here: https://github.com/defold/doc/blob/master/docs/en/manuals/editor.md

**Comment by Saikyun** [comment]
Added docs here. :) https://github.com/defold/doc/pull/137

**Comment by britzl** [comment]
Brilliant! Thank you for your contribution.

**Pull request merged**
