### PR TITLE
Bind Shift+Enter to find prev term in console

### LINKED ISSUE #6689: Shift+Enter in console search does not select previous match
**Describe the bug (REQUIRED)**
While <kbd>Enter</kbd> selects next match in the console search text field, <kbd>Shift+Enter</kbd> does not select the previous one.

**To Reproduce (REQUIRED)**
1. Launch a game
2. Focus on the Search input field in the console output pane
3. Type some text that is repeated in the logs multiple times
4. Press <kbd>Enter</kbd> to switch to the next match — it works
5. Press <kbd>Shift+Enter</kbd> to switch to the previous match — it doesn't work

**Expected behavior (REQUIRED)**
Shift+Enter in console search should select the previous match

### PR DESCRIPTION
**Pull request by vlaaad**
Fixes #6689

### CODE REVIEW

**Comment by AGulev** [comment]
pls update documentation https://github.com/defold/doc/blob/c21a1a6486165f93ad7d7faa575a8b1e3b8f9fdf/docs/en/manuals/editor-keyboard-shortcuts.md

**Comment by vlaaad** [comment]
Huh, I had no idea <kbd>Cmd G</kbd>/<kbd>Cmd Shift G</kbd> work there...

**Comment by vlaaad** [comment]
@AGulev  https://github.com/defold/doc/pull/274

**Review by matgis — APPROVED** [review]
Ship it!

**Pull request merged**
