### PR TITLE
Issue-4890-Backspace-should-work-with-a-Shift-pressed

### LINKED ISSUE #4890: Backspace key don't work inside an editor when there is also a Shift key pressed
**Describe the bug (REQUIRED)**
When I type something in a higher register (say a constant name or something alike) and suddenly want to delete some characters with a backspace, nothing happens. It's a common case which should work in IDEs out from the box and seems to be an easy win.

**To Reproduce (REQUIRED)**
1. Go to code editor (open lua code or anything in a text mode)
2. Type something with a Shift button pressed
3. Try to correct a text with a help of a Backspace key
4. Observe zero feedback from an editor (nothing was deleted)

**Expected behavior (REQUIRED)**
Text should be erased normally.

**Defold version (REQUIRED):**
  - Version: editor-dev branch actual for 9 of June 2020

**Platforms (REQUIRED):**
 - Platforms: any desktop platform
 - OS: Windows, macOS, Linux
 - Device: --

**Additional context (OPTIONAL):**
I found a reason why it happens in a code and willing to provide fix through PR

### PR DESCRIPTION
**Pull request by madwareru**
Closes #4890 
Closes defold/editor2-issues#1680

### CODE REVIEW

**Review by matgis-king — CHANGES_REQUESTED** [review]
We keep these lists sorted so it becomes easier to see which keyboard shortcuts are already taken. Please move the new entries so the lists remain sorted.

**Comment by vlaaad** [comment]
Works like a charm, thanks @madwareru! Please move the shortcuts to keep lists sorted and we'll be happy to merge.

**Comment by madwareru** [comment]
> We keep these lists sorted so it becomes easier to see which keyboard shortcuts are already taken. Please move the new entries so the lists remain sorted.

Seems to be in a right order now

**Review by matgis-king — APPROVED** [review]
Looks good to me!

**Review by eangelin — COMMENTED** [review]
Looks good to me :)

**Review by eangelin — APPROVED** [review]

**Pull request merged**
