### PR TITLE
DEF-3459 Android 64bit support

### PR DESCRIPTION
**Pull request by johan-becknoren-king**

### CODE REVIEW

**Review by mathiaswking — APPROVED** [review]
Looks good!

Some suggestions, and a few questions :)

**Review by matgis-king — COMMENTED** [review]
Looks good overall, and the editor bits seem to work well!

I did find some whitespace issues that I think we should address. I also found something that looked a bit off in `PlatformArchitectures.java`, although I didn't really look outside the Clojure stuff much.

**Review by andsveking — APPROVED** [review]
Reviewed latest Java changes related to new architecture support, looks good.

**Review by matgis-king — APPROVED** [review]
Looks good!

**Pull request merged**
