### PR TITLE
DEFEDIT-4875 Panel resize handles

### LINKED ISSUE #4875: Panel resize handle bars should be more visible.
**Is your feature request related to a problem? Please describe (REQUIRED):**
The grab handles for resizing panels in the editor are invisible. They're the same color as the menu bars, tab bars, status bar, and panel margins.

This means, if you resize the console panel all the way down or up, there's no visible way to undo it and it's stuck that way forever.

If you drag it all the way down it becomes invisible:
this

If you drag it all the way up, then it looks like the main editing window is gone.
[use your imagination here]

As of today, this problem has come up twice on the forum:
https://forum.defold.com/t/scene-view-is-lost/65439
https://forum.defold.com/t/bugs-in-defold-1-2-125-upd-not-only-in-125-solved/18791/20
Ah, another report here: https://github.com/defold/editor2-issues/issues/1714

**Describe the solution you'd like (REQUIRED):**
The bars need some sort of visual change so they're not invisible. They could be a different color, they could have some sort of textured "handle" in the middle so they look grabbable, etc. 

I think this kind of UI widget is called a "splitter"? Some little, flat-colored handle in the middle might fit the editor style (plus an outline or alternate base color).

**Describe alternatives you've considered (REQUIRED):**
I wouldn't like it, but I _guess_ an alternative solution would be to just limit the size of the console so it can't be resized all the way to one end or the other. For me those kinds of arbitrary limits are always way too large (like the assets panel has now). Sometimes you want to resize panels very small (or very large) but not hide them completely. Or maybe you _do_ want to hide it completely, but you'd rather drag it all the way small with the mouse than press a hotkey or go through a menu.

### PR DESCRIPTION
**Pull request by matgis-king**
### User-facing changes
* Add subtle resize handles to split panes in the main editor window.

### Technical changes
* Moved all non-main window styling out of `_split-pane.scss` to avoid applying it to other `SplitPanes`.

### CODE REVIEW

**Comment by eangelin** [comment]
Tested on mac, it's pretty subtle but I like it.

**Comment by vlaaad** [comment]
It's too subtle, I'd suggest making the default color to be the one that's currently used for hover, and making hover color MUCH more noticeable — see scroll bars for example of a control with a similar purpose.

**Comment by britzl** [comment]
One problem is that the handles become invisible when scaled down (since they consist of several lines instead of a solid shape), for instance the horizontal handle between Outline and Properties (which is very thin) and the vertical handle in the Curve editor (somewhat wider).

**Comment by matgis-king** [comment]
1. The handles are only drawn for the three main split dividers in the editor.
2. The subtlety is the point. I want the handles to be something you notice if you're looking for them, otherwise not.

Both of these are decisions, not mistakes.

**Comment by vlaaad** [comment]
I agree that subtlety is important for such rarely needed control, but I noticed them only because I knew they were there. Perhaps you can't see it's an issue because you have too good of a monitor with best in class colors? On my screen, they have sort of the same color as dust particles, making them almost invisible in daylight:
photo_2020-06-22_09-01-48

**Comment by matgis-king** [comment]
The bottom and right handles look fine to me, but the left one is nearly invisible. Strange. It is kind of hard to judge from the photo. Perhaps it would be best if you adjusted the two `-fx-opacity` values so it works for your screen and I can have a look over here afterwards?

**Comment by britzl** [comment]
Any update on this? Perhaps merge as is and get community feedback and perhaps a tweak or two if they aren't noticeable enough?

**Comment by vlaaad** [comment]
Sorry for delay, I'll look into it this evening

**Comment by vlaaad** [comment]
@matgis-king, please have a look! I think handles don't have to be as bright as scrollbars on hover since their hover area is the whole split (compared to scrollbar's hover area that is just a handle), so I made it less intense. Default opacity less than 0.1 is too hard to notice!

**Comment by matgis-king** [comment]
Thanks! I think it looks alright.

@britzl go ahead and merge if you're happy with it!

**Pull request merged**
