### PR TITLE
Fixed struct size calculation for buffer formats

### LINKED ISSUE #7599: Buffer is bigger than it can be
**Describe the bug (REQUIRED)**
Buffer size is bigger than it can be. Looks like it use biggest size of value for all streams.
For example. Second stream is x2 bigger then stream first.
```
const dmBuffer::StreamDeclaration chunk_buffer_decl1[] = {
    {HASH_CHUNK_DATA_1, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_2, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_3, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_4, dmBuffer::VALUE_TYPE_INT16, 1},
};

const dmBuffer::StreamDeclaration chunk_buffer_decl2[] = {
    {HASH_CHUNK_DATA_1, dmBuffer::VALUE_TYPE_FLOAT32, 1},
    {HASH_CHUNK_DATA_2, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_3, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_4, dmBuffer::VALUE_TYPE_INT16, 1},
};
```
```
INFO:GAME: data1 type:VALUE_TYPE_INT16 stride:4 
INFO:GAME: data2 type:VALUE_TYPE_INT16 stride:4 
INFO:GAME: data3 type:VALUE_TYPE_INT16 stride:4 
INFO:GAME: data4 type:VALUE_TYPE_INT16 stride:4 
INFO:GAME: Memory:64
INFO:GAME: -----------Buffer2-----------
INFO:GAME: data1 type:VALUE_TYPE_FLOAT32 stride:4 
INFO:GAME: data2 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: data3 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: data4 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: Memory:128
```

**To Reproduce (REQUIRED)**
I makre repro case and add logs.
```
const dmBuffer::StreamDeclaration chunk_buffer_decl1[] = {
    {HASH_CHUNK_DATA_1, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_2, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_3, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_4, dmBuffer::VALUE_TYPE_INT16, 1},
};

const dmBuffer::StreamDeclaration chunk_buffer_decl2[] = {
    {HASH_CHUNK_DATA_1, dmBuffer::VALUE_TYPE_FLOAT32, 1},
    {HASH_CHUNK_DATA_2, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_3, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_4, dmBuffer::VALUE_TYPE_INT16, 1},
};

const dmBuffer::StreamDeclaration chunk_buffer_decl3[] = {
    {HASH_CHUNK_DATA_1, dmBuffer::VALUE_TYPE_FLOAT32, 1},
    {HASH_CHUNK_DATA_2, dmBuffer::VALUE_TYPE_INT16, 2},
    {HASH_CHUNK_DATA_3, dmBuffer::VALUE_TYPE_INT16, 2},
    {HASH_CHUNK_DATA_4, dmBuffer::VALUE_TYPE_INT16, 2},
};

const dmBuffer::StreamDeclaration chunk_buffer_decl4[] = {
    {HASH_CHUNK_DATA_1, dmBuffer::VALUE_TYPE_INT16, 4},
    {HASH_CHUNK_DATA_2, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_3, dmBuffer::VALUE_TYPE_INT16, 1},
    {HASH_CHUNK_DATA_4, dmBuffer::VALUE_TYPE_INT32, 1},
};
```

```
INFO:GAME: -----------Buffer1-----------
INFO:GAME: data1 type:VALUE_TYPE_INT16 stride:4 
INFO:GAME: data2 type:VALUE_TYPE_INT16 stride:4 
INFO:GAME: data3 type:VALUE_TYPE_INT16 stride:4 
INFO:GAME: data4 type:VALUE_TYPE_INT16 stride:4 
INFO:GAME: Memory:64
INFO:GAME: -----------Buffer2-----------
INFO:GAME: data1 type:VALUE_TYPE_FLOAT32 stride:4 
INFO:GAME: data2 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: data3 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: data4 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: Memory:128
INFO:GAME: -----------Buffer3-----------
INFO:GAME: data1 type:VALUE_TYPE_FLOAT32 stride:4 
INFO:GAME: data2 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: data3 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: data4 type:VALUE_TYPE_INT16 stride:8 
INFO:GAME: Memory:128
INFO:GAME: -----------Buffer4-----------
INFO:GAME: data1 type:VALUE_TYPE_INT16 stride:10 
INFO:GAME: data2 type:VALUE_TYPE_INT16 stride:10 
INFO:GAME: data3 type:VALUE_TYPE_INT16 stride:10 
INFO:GAME: data4 type:VALUE_TYPE_INT32 stride:5 
INFO:GAME: Memory:160
```

**Expected behavior (REQUIRED)**
Buffer use as small size as possible.

**Defold version (REQUIRED):**
  - Version 1.4.4

**Minimal repro case project (OPTIONAL):**
[TestBuffers.zip](https://github.com/defold/defold/files/11304272/TestBuffers.zip)

**Additional context (OPTIONAL):**
https://forum.defold.com/t/how-can-i-reduce-buffer-size/73142

### PR DESCRIPTION
**Pull request by JCash**
The allocated buffers used too much memory due to a miscalculation in the struct size.

## PR checklist

* [-] Code
	* [x] Add engine and/or editor unit tests.
	* [x] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

**Review by Jhonnyg — APPROVED** [review]
👍

**Comment by AGulev** [comment]
Could you pls add task it fixes ? https://github.com/defold/defold/issues/7599

**Comment by JCash** [comment]
@AGulev I already did. It's in the "Development" list of issues to the right.

**Comment by AGulev** [comment]
@JCash 
ah, many ways to do the same. ok, I just see you don't have "Fix" comment and checkbox in the list, so decided to remind you.

**Pull request merged**
