### PR TITLE
fix misplaced docstrings

### PR DESCRIPTION
**Pull request by laurio**
A few docsctrings are placed after the binding form in the source code.

### CODE REVIEW

**Review by vlaaad — DISMISSED** [review]
Looks good to me!

**Comment by britzl** [comment]
@laurio thank you for the contribution. We are currently basing editor work off of the `editor-dev` branch and the engine development is based off of the `dev` branch. This is mentioned in the [contribution guidelines](https://github.com/defold/defold/blob/dev/CONTRIBUTING.md#pull-requests) but I think we either need to revise this way of working or make it much clearer to new contributors.

Could I please ask you to base this PR on editor-dev instead and merge it back there?

**Comment by laurio** [comment]
@britzl sorry, i didn't notice this part about the contribution guidelines. Changed the base to `editor-dev`.

**Comment by britzl** [comment]
Thank you for your contribution!

**Pull request merged**
