### PR TITLE
Update JavaFX

### LINKED ISSUE #6738: Defold editor crashes when dragging multiple assets
**Describe the bug (REQUIRED)**
Defold editor crashes when trying to drag files to a folder

**To Reproduce (REQUIRED)**
1. Select a couple files in Assets
2. Begin to drag
3. Crash

**Expected behavior (REQUIRED)**
Not a crash

**Defold version (REQUIRED):**
  - Version 1.3.3

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: macOS 11.6.5

**Logs (OPTIONAL):**
[java_2022-06-21-165429_dantalion.crash.zip](https://github.com/defold/defold/files/8953418/java_2022-06-21-165429_dantalion.crash.zip)

**Workaround (OPTIONAL):**
Selecting files one-by-one does not appear to crash.

**Additional context (OPTIONAL):**
It does not appear to matter what kind of files they are.

### PR DESCRIPTION
**Pull request by vlaaad**
User-facing changes: editor no longer crashes when dragging multiple items at the same time.

Fixes #6738

### CODE REVIEW

**Comment by AGulev** [comment]
Does it also help with https://github.com/defold/defold/issues/5047 ?

**Comment by vlaaad** [comment]
Unfortunately not

**Comment by vlaaad** [comment]
Or maybe it helps with the German layout, but it does not help the toggle comment shortcut on Swedish/Russian layouts

**Comment by vlaaad** [comment]
I now checked on macOS, Windows and Linux, and newer JavaFX seems to be working fine everywhere.

**Comment by vlaaad** [comment]
I only checked editor size difference on mac, it increased from 303Mb to 306Mb

**Review by matgis — APPROVED** [review]
LGTM!

**Pull request merged**
