### PR TITLE
Issue 5091: Ignore Mouse 4/5 buttons in editor

### LINKED ISSUE #5091: Mouse 4 and Mouse 5 throwing exceptions in Editor
**Describe the bug (REQUIRED)**
Whenever i press Mouse 4 or Mouse 5 in the Editor i get a window saying:

java.lang.IllegalArgumentException: No matching clause: FORWARD
or
java.lang.IllegalArgumentException: No matching clause: BACK

I have my Microphone Mute Button set to Mouse 4 so its quite frustrating.

**To Reproduce (REQUIRED)**
1. Fire up a Project
2. Press Mouse 4 or Mouse 5 Button
3. See error

**Expected behavior (REQUIRED)**
To put it simply: Nothing should happen.
If the keys are not bound there shouldn't be an exception

**Defold version (REQUIRED):**
  - Version 1.2.171

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Screenshots (OPTIONAL):**
image

**Additional context (OPTIONAL):**
<hr>
<table>
<tr><td>Build time</td><td>2020-08-10T10:25:52.880657</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ec66fdda665b28467177b20254c4e946b7e59e59</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0dd6607a35f94a7aa88a5bcf2a940e55"'>0dd6607a35f94a7aa88a5bcf2a940e55</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 451.67</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

### PR DESCRIPTION
**Pull request by alcorrius**
Fixes defold/defold#5091

### CODE REVIEW

**Review by vlaaad — APPROVED** [review]
LGTM

**Review by matgis — APPROVED** [review]
Looks good to me!

**Comment by britzl** [comment]
Thank you for your contribution @alcorrius !

**Comment by Alfagun74** [comment]
Took more than long enough to fix these couple of lines, thanks @alcorrius

**Pull request merged**
