### PR TITLE
Generate a build report for live update content

### LINKED ISSUE #3316: Build report should include Live Update resources. (DEF-3558)
In the build report, present any excluded resources as well (size, list resources etc.).

### PR DESCRIPTION
**Pull request by britzl**
The generated build reports will now also list excluded live update content in a separate report file.

```sh
java -jar bob.jar --verbose --platform=x86_64-macos --archive --liveupdate=yes --build-report=report.json --build-report-html=report.html clean build bundle
```

Will generate:

```
excluded_report.html
excluded_report.json
report.html
report.json
report_time.json
```

Fixes #3316

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

**Comment by AGulev** [comment]
But why time report is only in `json` in such case? If you make it possible to specify it separatly, maybe it worth to do the same for time_report as well?

**Comment by britzl** [comment]
> But why time report is only in `json` in such case? If you make it possible to specify it separately, maybe it worth to do the same for time_report as well?

Hmm, I haven't changed anything related to this. You've always been able to generate the report in two formats in the same run. But apparently this doesn't work for the time report. I can look into that.

**Comment by AGulev** [comment]
> You've always been able to generate the report in two formats in the same run.

I didn't know that! 
hmm, so, it's my fault I dind't take it into account

also this info maybe interesting for @ekharkunov-ms  (he asked about generation of the json and html reports at the same time a while ago)

**Review by AGulev — DISMISSED** [review]
LGTM, but it would be nice if you take a look why we don't build time report in both `json` and `html`

**Comment by britzl** [comment]
> LGTM, but it would be nice if you take a look why we don't build time report in both `json` and `html`

Done!

**Review by AGulev — APPROVED** [review]
I like it! Don't forget to update manual: https://defold.com/manuals/bob/

**Comment by britzl** [comment]
> Don't forget to update manual: https://defold.com/manuals/bob/

Done: https://github.com/defold/doc/commit/9164b483eee215902b8605cb8544fad70ec3edce

**Pull request merged**
