### PR TITLE
Defedit 1532 autocompletion for external libs

### PR DESCRIPTION
**Pull request by markusgustavssonking**
**User facing changes:** When adding a .script_api file to the project it will be used as a source for auto completions.

### CODE REVIEW

**Review by matgis-king — CHANGES_REQUESTED** [review]
Looks good overall, but seems like some parts are not completely finished yet (`eager-loading` & `additional-load-fn` for example). Also found a few things that I believe could be more efficient.

**Review by vlaaad — CHANGES_REQUESTED** [review]
Code good, though found a problem: invalid script_api files do not result in build errors, completions are just silently unavailable. Tried this file:
```
- name: beep
  type: function
  parameters: [{name: a, type: table}, {name: b}, {name: c}]
- name: boop
  type: table
  members: [{name: x, type: function, parameters: [{name: a}, {name: b}, {name: c}]}]
- name: bleep
  type: table
  members:
  - name: bloop
    type: table
    members: [{name: blah, type: function, parameters: [{name: n}]}]
- name: shmowp
---
  /// asd asd /as d//asd/ /asd //asd/ 
a/.d
 as
d
asd
a
sdasd
```

**Review by matgis-king — CHANGES_REQUESTED** [review]
Works great overall! But just like Vlad I did not get a Build Error for a broken file either.

**Review by matgis-king — CHANGES_REQUESTED** [review]
Just a minor thing about the Yaml error column being off by one and the message text needs trimming.

**Review by matgis-king — APPROVED** [review]
Ship it!

**Pull request merged**
