### PR TITLE
Add space between function arguments generated from .script_apis

### PR DESCRIPTION
**Pull request by JustAPotota**
Auto-complete doesn't put a space between arguments of functions defined in .script_api files, unlike all builtin functions.

Auto-complete with builtin functions:
builtin functions

Auto-complete with native extension functions:
native extension functions

### CODE REVIEW

**Comment by britzl** [comment]
Thanks. The PR looks good, but can I please ask that you change so that the target branch is `editor-dev` and not `dev`. The editor-dev branch is for editor-only changes and and merged PR will go live as soon as CI has built the new version.

https://github.com/defold/defold/blob/dev/CONTRIBUTING.md#pull-requests

**Comment by subsoap** [comment]
@britzl Since this keeps coming up maybe it should be more emphasized at the top of the docs somehow.

**Comment by JustAPotota** [comment]
@britzl It's now targeting `editor-dev`, though it seems to have dragged along several other commits with it (I assume from the `dev` branch).

**Comment by britzl** [comment]
You need to rebase or perhaps easier is to create a new PR starting from editor-dev.

**Comment by JustAPotota** [comment]
I'll just make a new PR. Apologies, I'm very new to this.

**Comment by JustAPotota** [comment]
New PR: https://github.com/defold/defold/pull/5407

**Pull request closed without merging**
