### PR TITLE
Upgrade to OpenJDK 17

### LINKED ISSUE #7767: Update JDK to 17
**Task (REQUIRED):**
Update used JDK version for editor and bob to 17

**Expected outcome (REQUIRED):**
We use JDK 17 so that we can update JavaFX that has fixes for e.g. hard crash on drag-n-drop of 2 items at the same time.

### PR DESCRIPTION
**Pull request by britzl**
User-facing changes:
Breaking change: migrate editor and bob to JDK 17.

Fixes #7767

### CODE REVIEW

**Review by vlaaad — DISMISSED** [review]
The editor seems to work!

**Comment by AGulev** [comment]
I remember @vlaaad mentioned that in newer java, it's possible to speed up the editor loading time using a sort of cache for classes or JVM byte code, I don't remember for sure
That would be nice to create a ticket about it for the future investigation

**Comment by vlaaad** [comment]
@AGulev probably this https://github.com/defold/defold/issues/4429

**Comment by AGulev** [comment]
image
https://cr.openjdk.org/~kcr/presentations/javaone-2022/JavaFX-19_Final.pdf

**Comment by vlaaad** [comment]
Hmm, why isn't it merged?

**Comment by AGulev** [comment]
javafx20 has been released (requires jdk 17)
https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-20.md

**Pull request merged**
