### PR TITLE
Exposed the `blend_mode` property on sprite components

### LINKED ISSUE #9292: Allow for sprite's Blend Mode to be updated programmatically
**Is your feature request related to a problem?**
I would like to change the Blend Mode of sprites programmatically.

Context: We have a lot of decals in our game, that we place using our custom level loader and I now have a "Decal" type, a "Screen Decal" type and a "Multiply Decal" type. Instead of a decal type with a Blend Mode property.

I can also imagine sprites changing Blend Mode based on game logics (e.g. Ghosts in Pacman changing appearance).

**Describe the solution you'd like:**
I would like to be able to change the Blend Mode of an instance of the sprite component of a game object:

```lua
msg.post(sprite_url, "blend_mode", sprite.BLEND_MULTIPLY)
```
or:
```lua
sprite.set_blend_mode(sprite_url, sprite.BLEND_SCREEN) -- like gui.set_blend_mode
```

Thanks!

### PR DESCRIPTION
**Pull request by ghost**
Exposed the `blend_mode` property on sprite components.

This allows the user to get and set a sprite's blend mode with `go.get()` and `go.set()`.

Resolves #9292 

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

**Comment by VowSoftware** [comment]
Having trouble getting Defold to recognize `blend_mode` as a property. I don't see any discrepancy between my code and the code that handles other properties, so I must be missing something.

```lua
go.get(msg.url(nil, hash("/terrain"), "sprite_albedo"), "blend_mode")
go.set(msg.url(nil, hash("/terrain"), "sprite_albedo"), "blend_mode", 4)
```

```
ERROR:SCRIPT: scripts/game.script:5: '[game:/terrain#sprite_albedo]' does not have any property called 'blend_mode'
```

(Setting the value to 4 is a temporary thing, since I haven't added blend mode enums to the `go` API yet.)

**Comment by Jhonnyg** [comment]
The code seems fine from my pov, in this case I would probably run the engine in a debugger to figure it out!

**Comment by VowSoftware** [comment]
> The code seems fine from my pov, in this case I would probably run the engine in a debugger to figure it out!

Is there documentation on how to run the engine through a debugger? Currently I just run unit tests with waf or launch the editor with lein, not sure how to work with this particular project when it comes to debugging.

**Comment by JCash** [comment]
We have some guides here:
https://defold.com/manuals/debugging-native-code/

**Pull request closed without merging**
