### PR TITLE
DEF-2477 build variants

### PR DESCRIPTION
**Pull request by danengelbrecht-king**
Added command line options for Bob --strip-executable and --variant=debug|release|headless
Added base variant manifests in SDK
Changed editor Release checkbox to variant popup
Embedds __base_variant in app manifest on the fly when requesting build from extender server

### CODE REVIEW

**Review by matgis-king — APPROVED** [review]
Editor changes look good!

**Review by matgis-king — COMMENTED** [review]
Clojure changes looks OK, just an indentation issue.

**Review by mathiaswking — CHANGES_REQUESTED** [review]
Looks good.
I'd like another stab at the option defaults etc (as I comment)

**Review by mathiaswking — APPROVED** [review]
Looks good apart from the returns code

**Pull request merged**
