### PR TITLE
DEFEDIT-1097 Checkbox in atlas to disable rotation when packing sprites

### PR DESCRIPTION
**Pull request by matgis-king**
Implements defold/editor2-issues#1134

### User-facing changes
* Altas resources now have an "Allow Rotation" checkbox which is enabled by default.
* Unchecking "Allow Rotation" packs all the sprites with their original image rotation.
* A new field for this property has been introduced in the file Atlas file format.

### CODE REVIEW

**Review by johan-becknoren-king — APPROVED** [review]
Looks good!

**Review by ragnard-king — APPROVED** [review]
Tested in editor2, works well!

**Comment by matgis-king** [comment]
@britzl I think we should close this. I seem to recall the discussion being that this should be a property on individual images rather than on the entire atlas.

The code change is trivial anyway, so there is not much value to it.

Let's revisit this issue if we decide to expand the atlas format with additional features in the future!

**Comment by britzl** [comment]
I agree. Let's close it.

**Pull request closed without merging**
