### PR TITLE
Removed old collada exporter with gpl license

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

**Review by britzl — APPROVED** [review]

**Comment by Exagone313** [comment]
Hi, I'd ask the lawyers if there is any issue with earlier builds containing GPLv2 code. Could that library's copyright holder ask for source code in GPLv2?

**Comment by subsoap** [comment]
@Exagone313 The .py scripts are aggregate. https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation

**Comment by Exagone313** [comment]
That link says `An “aggregate” consists of a number of separate programs`, which isn't the case here.

**Comment by subsoap** [comment]
@Exagone313 I'm not a Defold rep nor am I an expert. But it is a .py script on a git repo history so I don't know how else to define it than aggregate. Further, the resulting .jar referenced was never distributed to anyone afaik. It was not included in earlier builds, I even checked a bundle from 2016, it was part of an internal service. Correct me if I'm wrong.

**Pull request merged**
