### PR TITLE
Add "-keypass" parameter to Bob to allow a different key password

### LINKED ISSUE #5630: Add separate Android keystore password option to bob and the editor
**Is your feature request related to a problem? Please describe (REQUIRED):**
The Android keystore can use a different password from the password of the individual keys. This needs to be supported by bob and the editor.

**Describe the solution you'd like (REQUIRED):**
Bob must have an additional option to specify the keystore password and the key password

**Describe alternatives you've considered (REQUIRED):**
Make sure they are using the same password

**Additional context (OPTIONAL):**
https://forum.defold.com/t/android-keystore-file-and-alias-inside-it-should-have-the-same-passwords/67698?u=britzl

### PR DESCRIPTION
**Pull request by dri-richard**
This permits a key password to be passed to Bob for signing Android builds, in addition to the keystore password.

```
java -jar bob.jar --key-pass=mykeypass.txt --platform=armv7-android bundle
```

Fixes #5630

### CODE REVIEW

**Comment by britzl** [comment]
@dri-richard the reason #6051 wasn't completed was due to this finding that it was not possible in JDK11 and up to provide a different key and store password:

https://github.com/defold/defold/issues/5630#issuecomment-919736363

**Comment by dri-richard** [comment]
I made this change in a fork and am using it in our Github Action - I've built a bundle and upload it to Google Play without problems.
Perhaps the keytool limitation doesn't affect the Defold signing flow.

**Comment by britzl** [comment]
> I made this change in a fork and am using it in our Github Action

Hmm, ok, do you know which version of Java you are using?

**Comment by dri-richard** [comment]
> Hmm, ok, do you know which version of Java you are using?
$ javac --version
javac 11.0.14.1

**Review by britzl — APPROVED** [review]
Looks good! Thank you for the contribution.

**Comment by britzl** [comment]
> Looks good! Thank you for the contribution.

Although I now realise we need the same for the editor. I'll look into that.

**Review by britzl — CHANGES_REQUESTED** [review]
Also need editor support

**Pull request closed without merging**
