### PR TITLE
Linux editor: create desktop entry

### LINKED ISSUE #8095: Easier way to install Linux shortcut
**Is your feature request related to a problem? Please describe (REQUIRED):**
Users have to create their own .desktop file on Linux to create a desktop shortcut. We could provide that.

**Describe the solution you'd like (REQUIRED):**
Add an entry to the Help menu to create a .desktop file, just like JetBrains does:
Screenshot from 2023-10-05 15-36-44

**Describe alternatives you've considered (REQUIRED):**
* Add to the package an icon image file,  .desktop file and a shell script to setup this for the user. No editor code changes.

**Additional context (OPTIONAL):**
Related forum posts:
https://forum.defold.com/t/shortcut-for-linux/6035
https://forum.defold.com/t/start-linux-client-with-a-double-click/3691/5

I would love some guidance to get me started to make this happen

### PR DESCRIPTION
**Pull request by ivanquirino**
Adds a "Create Desktop Entry" menu entry in the help menu to make it easier for Linux users to install Defold on their desktops. Closes #8095.

* Includes `logo_blue.png` in the bundle
* Uses `xdg-desktop-menu` to install the file

image

https://github.com/defold/defold/assets/3946025/4a186c1a-ea8b-48ce-859f-f47dd30b6219

Docs PR: https://github.com/defold/doc/pull/365

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [x] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

**Comment by vlaaad** [comment]
Hey, thanks for the contribution!
Regarding your questions: when resources are not required to be files on a disc, we put them into the `editor/resources` folder. They are then packed into a jar file and available as Java resources (not files!) at runtime. This is an appropriate way to distribute a template for the desktop entry file (not sure we even need the file, we can store it in a string in code...). When it's imperative to have a file on disc, we have 2 ways to achieve this:
- unpacking resources at the start to a temporary directory (not applicable here since we need the file to be there when the editor is not running)
- adding a file to `editor/bundle-resources` and then changing [`bundle.py`'s `create_bundle`](https://github.com/defold/defold/blob/7e5c022ee89d625257f3e22797f49b51d60ba2ef/editor/scripts/bundle.py#L384) function to include the file on Linux. I think it makes sense to do it for the logo icon — we already do something similar for macOS there.

If you need to get a path to the executable used to launch the editor, you can use `editor.system/defold-launcherpath` fn. [See the example](https://github.com/defold/defold/blob/abcf38bc6f9b554e5277eb21d33fb3c3c664e283/editor/src/clj/editor/app_view.clj#L1582) for opening a new editor instance.

Implementation-wise, I think it's better to follow IntelliJ IDEA's approach, meaning:
- check for the command availability by checking if it's Linux and doing `which xdg-desktop-menu`, preferably only once.
- perform install by doing `xdg-desktop-menu install --mode user path-to-temp-file-with-prepared-desktop-entry`. We don't need to invoke `xdg-desktop-menu forceupdate` though since [it's only needed if we perform an install with `--noupdate` option](https://linux.die.net/man/1/xdg-desktop-menu).

**Comment by ivanquirino** [comment]
> Hey, thanks for the contribution! Regarding your questions: when resources are not required to be files on a disc, we put them into the `editor/resources` folder. They are then packed into a jar file and available as Java resources (not files!) at runtime. This is an appropriate way to distribute a template for the desktop entry file (not sure we even need the file, we can store it in a string in code...). When it's imperative to have a file on disc, we have 2 ways to achieve this:
> 
>     * unpacking resources at the start to a temporary directory (not applicable here since we need the file to be there when the editor is not running)
> 
>     * adding a file to `editor/bundle-resources` and then changing [`bundle.py`'s `create_bundle`](https://github.com/defold/defold/blob/7e5c022ee89d625257f3e22797f49b51d60ba2ef/editor/scripts/bundle.py#L384) function to include the file on Linux. I think it makes sense to do it for the logo icon — we already do something similar for macOS there.
> 
> 
> If you need to get a path to the executable used to launch the editor, you can use `editor.system/defold-launcherpath` fn. [See the example](https://github.com/defold/defold/blob/abcf38bc6f9b554e5277eb21d33fb3c3c664e283/editor/src/clj/editor/app_view.clj#L1582) for opening a new editor instance.
> 
> Implementation-wise, I think it's better to follow IntelliJ IDEA's approach, meaning:
> 
>     * check for the command availability by checking if it's Linux and doing `which xdg-desktop-menu`, preferably only once.
> 
>     * perform install by doing `xdg-desktop-menu install --mode user path-to-temp-file-with-prepared-desktop-entry`. We don't need to invoke `xdg-desktop-menu forceupdate` though since [it's only needed if we perform an install with `--noupdate` option](https://linux.die.net/man/1/xdg-desktop-menu).

All right, I'm going to change the entry template to a string in code and do the install using `xdg-desktop-menu`as you said. And also add the logo to editor/bundle-resources and patching bundle.py. I'll update this PR a later moment when I get this done (may take a moment because of job and life).

**Comment by ivanquirino** [comment]
@vlaaad `editor.system/defold-launcherpath` is returnin `nil`, in my current environment when running the editor using `lein run`, is that normal in dev or am I missing something?

**Comment by vlaaad** [comment]
Yes, it's only set in the bundle. This is why `open-project` action is disabled in the dev mode, for example: https://github.com/defold/defold/blob/abcf38bc6f9b554e5277eb21d33fb3c3c664e283/editor/src/clj/editor/app_view.clj#L1576

**Comment by ivanquirino** [comment]
> Yes, it's only set in the bundle. This is why `open-project` action is disabled in the dev mode, for example:
> 
> https://github.com/defold/defold/blob/abcf38bc6f9b554e5277eb21d33fb3c3c664e283/editor/src/clj/editor/app_view.clj#L1576

What is the difference between `enabled?` and `active?`? I suppose `enabled?` is whether to show or not the menu entry, and `active?` is whether to run the `run` fn or not. Is that correct?

**Comment by vlaaad** [comment]
IIRC, `active?` is whether it is shown, and `enabled?` is whether it can be run.

**Comment by ivanquirino** [comment]
> IIRC, `active?` is whether it is shown, and `enabled?` is whether it can be run.

so it is the other way around. Thanks for all the info and help. I am working on this today. 

On another side, I noticed that Defold is on the Homebrew package manager, and this raised on me the idea to provide Defold on the popular linux app stores, namely Flathub and Snap Store. I the same spirit as the Linux desktop entry, which is not a real necessity but something nice to have, and gives more polish and professionalism to Defold, distributing through app stores raises visibility, ease of install and OS integration for end users.

**Comment by vlaaad** [comment]
FYI, the [homebrew formula for Defold](https://github.com/Homebrew/homebrew-cask/blob/02c7aea45d2ec088186d8d596b99380be95bcd5a/Casks/d/defold.rb) is not maintained by the Defold team.

**Comment by vlaaad** [comment]
BTW, is it ready for review?

**Comment by ivanquirino** [comment]
> BTW, is it ready for review?

Not yet, I haven't tested it.

**Comment by ivanquirino** [comment]
Tested and ready for review!

**Comment by vlaaad** [comment]
Hey @ivanquirino, thanks for your PR! I've taken the liberty of adding some changes to it, as well as rebasing your commits onto the `editor-dev` branch so that the changes reach our users faster. You can follow further progress here: #8243

**Pull request closed without merging**
