### PR TITLE
Allow creating any file with any extension

### PR DESCRIPTION
**Pull request by vlaaad**
User-facing changes:
This changeset adds a new "File" option to the New File selector. When the option is selected, the user then can create any file with any extension. We still use file templates if the user types a registered file extension.

Technical notes:
I can't believe we didn't have it.

Related to #5301

### CODE REVIEW

**Review by matgis — CHANGES_REQUESTED** [review]
New feature works great, but it is now possible to name both New File and New Folder ".",  "..". This results in weirdness or an error, so it shouldn't be possible. You also shouldn't be able to create files or folders outside the project by typing in something like "../../new".

**Comment by vlaaad** [comment]
We filter out slashes, so it should be impossible to create files or folders outside of the project:
Screenshot 2024-01-19 at 09 22 49

**Comment by vlaaad** [comment]
Ah, you can type 2 dots and it will attempt to create a parent dir...

**Review by matgis — APPROVED** [review]
Ship it!

**Pull request merged**
