### PR TITLE
Update app icon for macOS Big Sur

### PR DESCRIPTION
**Pull request by dapetcu21**
This PR changes the editor's app and document icons to macOS Big Sur-friendly ones:

Defold - Icon - App - P3
Defold - Icon - Document - Centered Image - P3

Additionally, for Catalina and earlier, it falls back to this document icon:

Screenshot 2020-11-15 at 15 44 48

Here are the Photoshop projects (based on Apple's official templates) that I used to create these app icons:
[Archive.zip](https://github.com/defold/defold/files/5542447/Archive.zip)

### CODE REVIEW

**Comment by britzl** [comment]
Thank you!

I haven't upgraded to Big Sur yet myself. Did you encounter any other problems running Defold by the way?

**Comment by dapetcu21** [comment]
Not really. Apart from not being able to build the engine (which might have just been a case of "not tried hard enough"), everything seems to run exactly as it did on Catalina, engine and editor.

**Comment by britzl** [comment]
@dapetcu21 thanks. We have this reported issue: https://github.com/defold/defold/issues/5281 which is why I asked.

**Comment by dapetcu21** [comment]
I'm running on the integrated graphics, btw (UHD 630, i7 8600 on one computer and Iris 650, 13" 2017 MacBook Pro on the other). I can also try with an RX580 on the first one if you want me to.

**Review by JCash — APPROVED** [review]

**Pull request merged**
