### PR TITLE
Unify string representation of floats in userdata objects

### LINKED ISSUE #3810: Unify string representation of floats in userdata objects (vector3 etc) (DEF-1169)
Consider this:

local a = vmath.vector3(0, 0, math.pi)
pprint(a)

DEBUG:SCRIPT: vmath.vector3(0, 0, 3.1415927410126)

And the following:

print("vector is: " .. a)

DEBUG:SCRIPT: vector is: [0.000000, 0.000000, 3.141593]

Notice that the float numbers are printed differently. It would be nice if they were given the same representation in all cases.

### PR DESCRIPTION
**Pull request by sohamroy19**
Initial attempt to fix #3810.

Modified `__concat()` for Vector3, Vector4, Quat and Matrix4 to match the corresponding `__tostring()` output styles. Increasing extra reserved buffer could be unnecessary.
Note the remaining difference between the [Matrix4_tostring()](https://github.com/sohamroy19/defold/blob/0092a4cdbd12d03faa9adb193e15ff6a7f2b05fb/engine/script/src/script_vmath.cpp#L623) and the [Matrix4_concat()](https://github.com/sohamroy19/defold/blob/0092a4cdbd12d03faa9adb193e15ff6a7f2b05fb/engine/script/src/script_vmath.cpp#L727). Which style should we go ahead with?

Regarding the number of decimal digits, I think that can be attributed to `__tostring()` using the internal [engine/lua/src/lua/lobject.c](https://github.com/defold/defold/blob/da10b2415b5dceab746a1e0478e0c63897dc0623/engine/lua/src/lua/lobject.c#L138-L142) whereas `__concat()` [calls standard functions](https://github.com/defold/defold/blob/da10b2415b5dceab746a1e0478e0c63897dc0623/engine/dlib/src/dlib/dstrings.cpp#L30-L34). How can we proceed?

### CODE REVIEW

**Comment by britzl** [comment]
> Note the remaining difference between the [Matrix4_tostring()](https://github.com/sohamroy19/defold/blob/0092a4cdbd12d03faa9adb193e15ff6a7f2b05fb/engine/script/src/script_vmath.cpp#L623) and the [Matrix4_concat()](https://github.com/sohamroy19/defold/blob/0092a4cdbd12d03faa9adb193e15ff6a7f2b05fb/engine/script/src/script_vmath.cpp#L727). Which style should we go ahead with?

I think we should be consistent and start with vmath.matrix4. The `| ` as a divider between the rows should perhaps be copied from `__concat`?

> Regarding the number of decimal digits, I think that can be attributed to `__tostring()` using the internal [engine/lua/src/lua/lobject.c](https://github.com/defold/defold/blob/da10b2415b5dceab746a1e0478e0c63897dc0623/engine/lua/src/lua/lobject.c#L138-L142) whereas `__concat()` [calls standard functions](https://github.com/defold/defold/blob/da10b2415b5dceab746a1e0478e0c63897dc0623/engine/dlib/src/dlib/dstrings.cpp#L30-L34). How can we proceed?

`lua_pushfstring` uses `sprintf` while `dmSnPrintf` uses `vsnprintf`. Both should have a default precision of 6 but there's obviously some difference in how the number is formatted. I think we could avoid this by explicitly specifying precision etc. I'm not sure it's worth it, but perhaps you can research which format specifiers we need to make both functions output the same result?

**Comment by sohamroy19** [comment]
Agreed, `| ` seems better- switched to it in https://github.com/defold/defold/pull/6092/commits/4fd39bbd2c6471e59afe6d79cd3d4014bbad939d. Will investigate decimal precision later.

**Review by britzl — APPROVED** [review]
Looks good! Thank you.

**Review by britzl — CHANGES_REQUESTED** [review]
Thanks. Just noticed a difference in naming convention. Could you please fix this and then I'll merge it?

**Review by britzl — APPROVED** [review]
Thanks. Well done!

**Pull request merged**
