### PR TITLE
Added engine.max_time_step config value

### LINKED ISSUE #9252: Add option to set max frame delta time
**Is your feature request related to a problem? Please describe (REQUIRED):**
Players can unintentionally make the game have a very high delta time. Consequences of this: visually missed animations and physical objects stuck in each other.

On Windows you have to resize the window to achieve this. On HTML5 you just have to switch to another tab. Or simply the device can slow down for a moment due to watching a movie in parallel (just kidding, but on 2-4 core PCs you can do this just by starting to open another application). 

How we deal with this: HTML5 tab focus change can be tracked with `window.set_listener` to pause/unpause the collection proxy. But the window "resize" event or a computer that freezes for half a second is impossible to track.

OK, if your game is built around fixed update, it's not a big problem if it misses 0.5 seconds - nothing will break and the engine will "catch up" the missed frames by itself. But it is very difficult to make games with fixed update, because you have to separate visual and logical parts to interpolate the movement from 60hz fixed step to 144hz player monitors.

**So, the point of the request is:** I want to simplify the development of my simple 2D games with this max frame time limitation. So that I don't have to write a ton of extra checks on whether a window is open or closed or resized or maximized and so on. I'm going to set this cap at **0.05 sec** and it will solve most of my issues (and I'll even remove most of the code with workarounds). 

**Describe the solution you'd like (REQUIRED):**
Add an option to the game.project Display section: "Max Frame Delta Time". Leave 0.5 by default, as it is hard-coded in the engine - https://github.com/defold/defold/blob/7c4575d68b3ba8daf87e78f13fc72d8c071e012f/engine/engine/src/engine.cpp#L1812

### PR DESCRIPTION
**Pull request by JCash**
In case the engine timestep grows too large, it will be capped against this max value (default is 0.5 seconds)

Fixes https://github.com/defold/defold/issues/9252

## PR checklist

* [ ] Code
	* [ ] Add engine and/or editor unit tests.
	* [ ] New and changed code follows the overall code style of existing code
	* [ ] Add comments where needed
* [ ] Documentation
	* [ ] Make sure that API documentation is updated in code comments
	* [ ] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [ ] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [ ] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "breaking change" label to the issue if introducing a breaking change.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

----------

Example of a well written PR description:

1. Start with the user facing changes. This will end up in the release notes.
1. Add one of the GitHub approved closing keywords
1. Optionally also add the technical changes made. This is information that might help the reviewer. It will not show up in the release notes. Technical changes are identified by a line starting with one of these:
   1. `### Technical changes` 
   1. `Technical changes:`
   2. `Technical notes:`

```
There was a anomaly in the carbon chroniton propeller, introduced in version 8.10.2. This fix will make sure to reset the phaser collector on application startup.

Fixes #1234

### Technical changes
* Pay special attention to line 23 of phaser_collector.clj as it contains some interesting optimizations
* The propeller code was not taking into account a negative phase.
```

### CODE REVIEW

**Review by AGulev — DISMISSED** [review]
🔥

**Comment by AGulev** [comment]
>Assign the issue to a project. **Do not assign the pull request to a project if there is an issue which the pull request closes.**

**Comment by aglitchman** [comment]
🤗

**Review by AGulev — APPROVED** [review]

**Comment by aglitchman** [comment]
I couldn't resist and already checked the option and the ALPHA version of Defold on Puffy Cat, i.e. we disabled `use fixed timestep` for physics, set max time step = 0.05. The game works now without problems even on super slow phones and we completely eliminated 2d physics jittering. Yay!

**Pull request merged**
