### PR TITLE
HTML5: Allow memory growth

### PR DESCRIPTION
**Pull request by aglitchman**
**The pull request is not ready to be reviewed!** I use Github Actions' powers to test the idea of allowing memory growth for HTML5 builds mentioned in https://github.com/defold/defold/issues/5411.

If it succeeds, I'll add more info.

### CODE REVIEW

**Comment by dapetcu21** [comment]
I'm not sure this is the best thing to do. That flag shouldn't be applied to asm.js builds since it disables asm.js optimizations. It should only be applied to wasm.

**Comment by aglitchman** [comment]
> I'm not sure this is the best thing to do. That flag shouldn't be applied to asm.js builds since it disables asm.js optimizations. It should only be applied to wasm.

Good point!

The pull request was created to test the performance of the engine with that flag.

Unfortunately, CI builds the source code of the dev branch without my changes, i.e. CI builds the commit 1c6c20597a38dcc202d29774be1878dbcef33ede, and [uploaded SDK](https://d.defold.com/archive/alpha/1c6c20597a38dcc202d29774be1878dbcef33ede/engine/defoldsdk.zip) doesn't have modified lines in the `extender/build.yml` file.

**Comment by aglitchman** [comment]
I'm going to test it locally. I'll post results here.

**Comment by aglitchman** [comment]
Closed because of https://github.com/defold/defold/pull/5446

**Pull request closed without merging**
