### PR TITLE
Issue-5851 Fix android gamepad issues

### LINKED ISSUE #5851: Triggers, Hats and Guide buttons don't work on Android
**Describe the bug (REQUIRED)**
Triggers, Hats and Guide buttons don't work on Android

**Defold version (REQUIRED):**
  - Version 1.2.183

**Platforms (REQUIRED):**
 - OS: Android

### PR DESCRIPTION
**Pull request by AGulev**
* Fix issue with GUIDE button
* Fix issue with Triggers
* Fix issue with Hats
* Added new default gamepads: Dualshock4 and Xbox

More info is here: https://forum.defold.com/t/defold-1-2-183-beta/68455/18?u=agulev

Fix https://github.com/defold/defold/issues/5851

### CODE REVIEW

**Review by britzl — DISMISSED** [review]
Looks good!

**Comment by AGulev** [comment]
https://user-images.githubusercontent.com/2209596/120925941-25d84500-c6db-11eb-8dcc-8724644d1286.mp4

@britzl could you please take a look one more time. I fixed Hats for Android.

**Comment by AGulev** [comment]
I kept both because according to the docs hats may work both ways: as axis and as dpads.
image

**Review by britzl — APPROVED** [review]
Great! 👍

**Pull request merged**
