### PR TITLE
Added missing types in documentation for "to" parameter in gui.animate and for "value" in go.property

### PR DESCRIPTION
**Pull request by mikatuo**
The number and quaternion were missing from the list of accepted types.

## PR checklist

* [x] Documentation
	* [x] Make sure that API documentation is updated in code comments
	* [x] Make sure that manuals are updated (in github.com/defold/doc)
* [ ] Prepare pull request and affected issue for automatic release notes generator
	* [x] Pull request - Write a message that explains what this pull request does. What was the problem? How was it solved? What are the changes to APIs or the new APIs introduced? This message will be used in the generated release notes. Make sure it is well written and understandable for a user of Defold.
	* [x] Pull request - Write a pull request title that in a sentence summarises what the pull request does. Do not include "Issue-1234 ..." in the title. This text will be used in the generated release notes.
	* [ ] Pull request - Link the pull request to the issue(s) it is closing. Use on of the [approved closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
	* [ ] Affected issue - Assign the issue to a project. Do not assign the pull request to a project if there is an issue which the pull request closes.
	* [ ] Affected issue - Assign the "skip release notes" is the issue should not be included in the generated release notes.

### CODE REVIEW

**Comment by mikatuo** [comment]
There might be another type missing for `go.property`, but I'm not sure how to properly add it into the comments.
Should it be added somewhere here as a new comment block? https://github.com/defold/defold/blob/8bfa5c6146045dc8a40ec2d8fab218232ed75c49/engine/gameobject/src/gameobject/gameobject_script.cpp#L63

**Review by britzl — DISMISSED** [review]

**Comment by britzl** [comment]
> There might be a type missing for `go.property` as well, but I'm not sure how to properly add it into the comments.

Ah, it should be added here: https://github.com/defold/defold/blob/8bfa5c6146045dc8a40ec2d8fab218232ed75c49/engine/gameobject/src/gameobject/gameobject_script.cpp#L2062

**Comment by mikatuo** [comment]
Should I update `go.property` in this PR or a new one?

**Comment by britzl** [comment]
> Should I update `go.property` in this PR or a new one?

You can do it in this one!

**Review by britzl — APPROVED** [review]

**Comment by britzl** [comment]
Thank you!

--skip-ci

**Pull request merged**
