### PR TITLE
Issue 5728: Enable dynamic transforms by default

### LINKED ISSUE #5728: Suggestion: allow dynamic transforms by default
**Is your feature request related to a problem? Please describe (REQUIRED):**
I was frustrated debugging a physics issue with an object which changes size dynamically. Eventually, I realized that its collision object wasn't scaling with it. After 30 minutes of Googling this issue, I realized that Defold already has the ability to handle this properly, but it's disabled by default. While I don't fully understand the performance impact of this, I think that it makes much more sense to enable this by default, because I can see from past threads on the forums that many other people are having this same issue.

**Describe the solution you'd like (REQUIRED):**
I think that unless the performance impact is large, the default setting for "Allow Dynamic Transforms" should be enabled. 

**Describe alternatives you've considered (REQUIRED):**
I considered using a kinematic object instead of a dynamic one, but I want my object to be affected by gravity, and to bounce of other objects. But I still want to scale it. I can use a workaround of deleting and recreating the collision object, but this keeps my code much more clean. 

This is of course, just my suggestion. And if the performance impact is too high, then it no longer makes sense. The documentation says quite clearly that you can't control the position/rotation/scale of a dynamic object, but what makes it confusing it that you *can* control the scale of an object, but its collision object won't change by default, and there's no warning/error. So a lot of people get confused when they see the physics of the object, and have to spend time debugging.

### PR DESCRIPTION
**Pull request by Reubend**
fixes https://github.com/defold/defold/issues/5728

### CODE REVIEW

**Comment by britzl** [comment]
I'm just leaving a note here that we need to update the docs: https://github.com/defold/doc/blob/master/docs/en/manuals/physics-shapes.md#scaling-collision-shapes

**Comment by subsoap** [comment]
https://github.com/defold/defold/blob/1ae302ec33d4514408c04ad3ae5d3c1efe2057bd/engine/engine/src/engine.cpp#L951

Does this line need to be changed as well? It defaults to 0 atm I think?

**Comment by Reubend** [comment]
> https://github.com/defold/defold/blob/1ae302ec33d4514408c04ad3ae5d3c1efe2057bd/engine/engine/src/engine.cpp#L951
> 
> Does this line need to be changed as well? It defaults to 0 atm I think?

Good call, fixed!

**Review by JCash — APPROVED** [review]
Looks good.

**Pull request merged**
