### PR TITLE
Issue 5249: sys.exit() works again on Android

### LINKED ISSUE #5249: After closing app using `exit` msg and open again see just black screen.
**Describe the bug (REQUIRED)**
If I close a game using `exit` mesage and open the game again I see just a black screen.

**To Reproduce (REQUIRED)**
1. Create exit button with the following code on it:
```
  if action_id == BACK_KEY and action.released then
    print("Time to exit!")
    msg.post("@system:", "exit", {code = 0})
  end
```
2. Run this app on Android
3. Tap exit button
4. Open the app again
5. black screen here

**Expected behavior (REQUIRED)**
App opens without any problems

**Defold version (REQUIRED):**
  - Defold 1.2.174 
Editor SHA: 5d8d6d6ed04e9d6ed8c577e558f6ad767e2e3735
Engine SHA: 5d8d6d6ed04e9d6ed8c577e558f6ad767e2e3735

**Platforms (REQUIRED):**
 - Platforms: Android
 - OS: 10
 - Device: Samsung s10e, Samsung s20, Huawei P20 Pro

(I can't reproduce this issue on Xiaomi Redmi Note 4 with Android 6)

**Minimal repro case project (OPTIONAL):**
https://github.com/AGulev/DefVideoAds
(Exit on Back button)

**Logs (OPTIONAL):**
[log.log](https://github.com/defold/defold/files/5300914/log.log)

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

**Comment by JCash** [comment]
Now the app closes with the:

```
...
10-01 10:49:25.849 25183 25183 V threaded_app: Stop: 0x7eb398b040
10-01 10:49:25.849 25183 25219 V threaded_app: activityState=14
10-01 10:49:25.849 25183 25219 V glfw-android: handleCommand: APP_CMD_STOP
10-01 10:49:25.853 25183 25183 V threaded_app: InputQueueDestroyed: 0x7eb398b040 -- 0x7eb398cbc0
10-01 10:49:25.853 25183 25219 V threaded_app: APP_CMD_INPUT_CHANGED
10-01 10:49:25.854 25183 25219 V glfw-android: handleCommand: APP_CMD_INPUT_CHANGED
10-01 10:49:25.854 25183 25183 V threaded_app: Destroy: 0x7eb398b040
10-01 10:49:25.854 25183 25219 V threaded_app: APP_CMD_DESTROY
10-01 10:49:25.854 25183 25219 V glfw-android: handleCommand: APP_CMD_DESTROY
10-01 10:49:25.854 25183 25219 V glfw-android: final_gl
10-01 10:49:26.234  3832  5253 I ActivityManager: Process com.example.todo (pid 25183) has died: cch  CRE (166,1703)
10-01 10:49:26.235  3832  3861 W libprocessgroup: kill(-25183, 9) failed: No such process
10-01 10:49:26.235  3832  3861 I libprocessgroup: Successfully killed process cgroup uid 10328 pid 25183 in 0ms
10-01 10:49:26.236  3442  3442 I Zygote  : Process 25183 exited cleanly (0)
10-01 10:49:26.246  3832  3868 W ActivityManager: setHasOverlayUi called on unknown pid: 25183
```

**Review by britzl — APPROVED** [review]

**Comment by AGulev** [comment]
If I understand correctly this fix will be included in 1.2.175?

**Comment by britzl** [comment]
@AGulev it's actually part of the 174 release.

**Comment by AGulev** [comment]
Great!

**Pull request merged**
